/*
AUTOR: <EDUARDO PEREZ>
FECHA: <2020-12-29>
DESCRIP: <SE CREA UNA NUEVA BASE TPROWS PARA ALMACENAR ESTA TABLA EN ESTE LUGAR
          POR SOLICITUD DE CARLITOS ESTA CONTIENE LA NOMINA CONFIDENCIAL>


exec [dbo].[spBBDD_Inactivos_NC]
*/

select top 10 *
from tbccmsactivos